ğŸŒµroot:
  - changed-files:
      - any-glob-to-any-file: '*'

public:
  - changed-files:
    - any-glob-to-any-file: '**/public/**'

â›²source:
  - changed-files:
    - any-glob-to-any-file: '**/src/**'
    - all-globs-to-all-files: ['!**/*.test.*', '!**/*.spec.*', '!**/test/**']

ğŸ§ª test:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.*', '**/*.spec.*', '**/test/**']

ğŸ‡¹typescript:
  - changed-files:
      - any-glob-to-any-file:
        - '**/*.ts'
        - '**/*.tsx'

ğŸ‡¯javascript:
  - changed-files:
      - any-glob-to-any-file:
        - '**/*.js'
        - '**/*.jsx'

ğŸˆ¸ app:
  - changed-files:
      - any-glob-to-any-file: ['apps/**']

ğŸ“š library:
  - changed-files:
      - any-glob-to-any-file: ['libs/**', 'cmps/**']

ğŸ§± component:
  - changed-files:
      - any-glob-to-any-file:
        - '**/*.jsx'
        - '**/*.tsx'

ğŸ“¦ packaging:
  - changed-files:
      - any-glob-to-any-file: ['**/package.json', '**/package.yaml', '**/pnpm-lock.yaml', '**/package-lock.lock','**/yarn.lock']

ğŸ“œ documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', '**/*.MD', '**/docs/*']

ğŸ³ docker:
  - changed-files:
      - any-glob-to-any-file: [ '**/Dockerfile' ]

ğŸ”„ ci:
  - changed-files:
      - any-glob-to-any-file:
        - .github/**
