scraper: PealimScraper
baseUrl: https://www.pealim.com
delayMs: 200
fromIndex: 604
iterations: -1
bootSequence:
  - PealimScraper
roots:
  - אבב
  - אבד
  - אבה
  - אבכ
  - אבל
  - אבנ
  - אבס
  - אבק
  - אבר
  - אגד
  - אגז
  - אגל
  - אגמ
  - אגנ
  - אגפ
  - אגר
  - אדב
  - אדמ
  - אדנ
  - אדר
  - אהב
  - אהה
  - אהל
  - אוב
  - אוד
  - אוה
  - אוח
  - אול
  - אומ
  - אונ
  - אוצ
  - אור
  - אות
  - אזב
  - אזה
  - אזל
  - אזנ
  - אזק
  - אזר
  - אחד
  - אחה
  - אחז
  - אחר
  - אחש
  - אטד
  - אטט
  - אטמ
  - אטנ
  - אטר
  - איב
  - איה
  - איל
  - אימ
  - אינ
  - איש
  - אכל
  - אכפ
  - אכר
  - אלה
  - אלח
  - אלל
  - אלמ
  - אלפ
  - אלצ
  - אמה
  - אמל
  - אממ
  - אמנ
  - אמצ
  - אמר
  - אמש
  - אנב
  - אנה
  - אנח
  - אנכ
  - אננ
  - אנס
  - אנפ
  - אנק
  - אנש
  - אסמ
  - אסנ
  - אספ
  - אסר
  - אפד
  - אפה
  - אפל
  - אפנ
  - אפס
  - אפפ
  - אפק
  - אפר
  - אצל
  - אצר
  - אקה
  - ארב
  - ארג
  - ארה
  - ארז
  - ארח
  - ארכ
  - ארמ
  - ארצ
  - ארר
  - ארש
  - ארשׂ
  - אשד
  - אשה
  - אשכ
  - אשל
  - אשמ
  - אשפ
  - אשר
  - אשש
  - אשת
  - אתה
  - אתנ
  - אתק
  - אתר
  - אתת
  - באר
  - באש
  - בבה
  - בגד
  - בגה
  - בדא
  - בדד
  - בדה
  - בדל
  - בדק
  - בהה
  - בהט
  - בהל
  - בהמ
  - בהנ
  - בהק
  - בהר
  - בוא
  - בוז
  - בוכ
  - בול
  - בומ
  - בונ
  - בוס
  - בוצ
  - בוק
  - בור
  - בוש
  - בזא
  - בזה
  - בזז
  - בזק
  - בזר
  - בחה
  - בחל
  - בחנ
  - בחר
  - בטא
  - בטה
  - בטח
  - בטל
  - בטנ
  - ביה
  - בינ
  - ביר
  - בית
  - בכא
  - בכה
  - בכר
  - בלא
  - בלג
  - בלה
  - בלל
  - בלמ
  - בלס
  - בלע
  - בלק
  - במה
  - בנה
  - בנט
  - בננ
  - בסס
  - בסר
  - בעד
  - בעה
  - בעט
  - בעל
  - בער
  - בעת
  - בצא
  - בצה
  - בצל
  - בצע
  - בצצ
  - בצק
  - בצר
  - בקע
  - בקק
  - בקר
  - בקש
  - ברא
  - ברד
  - ברה
  - ברז
  - ברח
  - ברכ
  - ברמ
  - ברק
  - ברר
  - ברש
  - ברת
  - בשל
  - בשׂמ
  - בשס
  - בשׂר
  - בשש
  - בתה
  - בתל
  - בתק
  - בתר
  - בתת
  - גאה
  - גאל
  - גבא
  - גבב
  - גבה
  - גבח
  - גבל
  - גבנ
  - גבע
  - גבר
  - גבש
  - גגג
  - גדד
  - גדה
  - גדל
  - גדע
  - גדפ
  - גדר
  - גדש
  - גהה
  - גהר
  - גוא
  - גוב
  - גוד
  - גוה
  - גוז
  - גוח
  - גול
  - גוע
  - גופ
  - גור
  - גוש
  - גזה
  - גזז
  - גזל
  - גזמ
  - גזע
  - גזר
  - גחל
  - גלב
  - גלד
  - גלה
  - גלח
  - גלל
  - גלמ
  - גלע
  - גלש
  - גמא
  - גמד
  - גמה
  - גמל
  - גמצ
  - גמר
  - גנב
  - גנז
  - גננ
  - געה
  - געל
  - גער
  - געש
  - גפפ
  - גפר
  - גרב
  - גרד
  - גרה
  - גרז
  - גרל
  - גרמ
  - גרס
  - גרע
  - גרפ
  - גרר
  - גרש
  - גרשׂ
  - גשמ
  - גשש
  - גתת
  - דאב
  - דאג
  - דאה
  - דבא
  - דבב
  - דבה
  - דבל
  - דבק
  - דבר
  - דבש
  - דגה
  - דגל
  - דגנ
  - דגר
  - דדא
  - דדד
  - דדה
  - דהב
  - דהמ
  - דהר
  - דוב
  - דוג
  - דוד
  - דוה
  - דוח
  - דוכ
  - דומ
  - דונ
  - דוצ
  - דוק
  - דור
  - דוש
  - דות
  - דחה
  - דחח
  - דחנ
  - דחפ
  - דחק
  - דיה
  - דינ
  - דכא
  - דכה
  - דככ
  - דכפ
  - דלג
  - דלה
  - דלח
  - דלל
  - דלפ
  - דלק
  - דמה
  - דממ
  - דמנ
  - דמע
  - דנג
  - דננ
  - דעכ
  - דפה
  - דפק
  - דקל
  - דקק
  - דקר
  - דרא
  - דרב
  - דרג
  - דרכ
  - דרר
  - דרש
  - דשא
  - דשנ
  - הבב
  - הבה
  - הבל
  - הבנ
  - הבר
  - הגג
  - הגה
  - הגנ
  - הגר
  - הדד
  - הדה
  - הדכ
  - הדמ
  - הדס
  - הדפ
  - הדר
  - ההה
  - הוא
  - הוד
  - הוה
  - הומ
  - הונ
  - הזה
  - היה
  - הימ
  - הינ
  - הכר
  - הלא
  - הלה
  - הלכ
  - הלל
  - הלמ
  - המה
  - המל
  - הממ
  - המס
  - המר
  - הנה
  - הננ
  - הסה
  - הפכ
  - הצנ
  - הרג
  - הרה
  - הרס
  - הרר
  - התל
  - התת
  - זאב
  - זאה
  - זבב
  - זבד
  - זבח
  - זבל
  - זגג
  - זהב
  - זהה
  - זהמ
  - זהר
  - זוב
  - זוד
  - זוה
  - זוז
  - זוח
  - זול
  - זונ
  - זוע
  - זוק
  - זור
  - זות
  - זחח
  - זחל
  - זיו
  - זכה
  - זככ
  - זכר
  - זלג
  - זלל
  - זמה
  - זממ
  - זמנ
  - זמר
  - זנב
  - זנה
  - זנח
  - זנק
  - זעה
  - זעכ
  - זעמ
  - זעע
  - זעפ
  - זעק
  - זער
  - זפפ
  - זקה
  - זקנ
  - זקפ
  - זקק
  - זרא
  - זרב
  - זרה
  - זרז
  - זרח
  - זרמ
  - זרע
  - זרפ
  - זרק
  - זרר
  - חבא
  - חבב
  - חבה
  - חבט
  - חבל
  - חבק
  - חבר
  - חבש
  - חבת
  - חגא
  - חגב
  - חגג
  - חגה
  - חגר
  - חדד
  - חדה
  - חדל
  - חדק
  - חדר
  - חדש
  - חוב
  - חוג
  - חוד
  - חוה
  - חוז
  - חוח
  - חוט
  - חול
  - חומ
  - חונ
  - חוס
  - חופ
  - חוצ
  - חוק
  - חור
  - חוש
  - חות
  - חזה
  - חזז
  - חזק
  - חזר
  - חטא
  - חטב
  - חטה
  - חטמ
  - חטפ
  - חטר
  - חיה
  - חיי
  - חיל
  - חיק
  - חכה
  - חככ
  - חכל
  - חכמ
  - חלא
  - חלב
  - חלד
  - חלה
  - חלט
  - חלל
  - חלמ
  - חלפ
  - חלצ
  - חלק
  - חלש
  - חמא
  - חמד
  - חמה
  - חמט
  - חמל
  - חממ
  - חמס
  - חמצ
  - חמק
  - חמר
  - חמש
  - חנה
  - חנט
  - חנכ
  - חננ
  - חנפ
  - חנק
  - חסד
  - חסה
  - חסל
  - חסמ
  - חסנ
  - חסס
  - חספ
  - חסר
  - חפא
  - חפה
  - חפז
  - חפנ
  - חפפ
  - חפצ
  - חפר
  - חפש
  - חפשׂ
  - חצב
  - חצה
  - חצנ
  - חצצ
  - חצר
  - חקה
  - חקק
  - חקר
  - חרא
  - חרב
  - חרג
  - חרד
  - חרה
  - חרז
  - חרט
  - חרכ
  - חרל
  - חרמ
  - חרס
  - חרפ
  - חרצ
  - חרק
  - חרר
  - חרש
  - חרשׂ
  - חרת
  - חשב
  - חשה
  - חשכ
  - חשׂכ
  - חשל
  - חשמ
  - חשנ
  - חשׂפ
  - חשק
  - חשר
  - חשש
  - חתה
  - חתכ
  - חתל
  - חתמ
  - חתנ
  - חתפ
  - חתר
  - חתת
  - טבח
  - טבל
  - טבע
  - טבר
  - טהר
  - טוא
  - טוב
  - טוה
  - טוח
  - טוט
  - טול
  - טופ
  - טור
  - טושׂ
  - טחה
  - טחח
  - טחנ
  - טחר
  - טלא
  - טלה
  - טלל
  - טלפ
  - טמא
  - טמה
  - טממ
  - טמנ
  - טנא
  - טנפ
  - טעה
  - טעמ
  - טענ
  - טפח
  - טפל
  - טפפ
  - טפש
  - טרד
  - טרה
  - טרח
  - טרפ
  - יאב
  - יאה
  - יאל
  - יאר
  - יאש
  - יבב
  - יבל
  - יבמ
  - יבש
  - יגב
  - יגה
  - יגל
  - יגע
  - יגר
  - ידד
  - ידה
  - ידע
  - יהב
  - יהד
  - יהה
  - יהר
  - יוה
  - יומ
  - יונ
  - יזמ
  - יזנ
  - יזע
  - יחד
  - יחל
  - יחמ
  - יחפ
  - יחשׂ
  - יטב
  - יינ
  - יככ
  - יכל
  - ילד
  - ילל
  - ילע
  - ילפ
  - ילק
  - ימכ
  - יממ
  - ימנ
  - ימר
  - ינה
  - ינס
  - ינק
  - יסד
  - יספ
  - יסר
  - יעד
  - יעה
  - יעז
  - יעט
  - יעל
  - יעפ
  - יעצ
  - יער
  - יפה
  - יפח
  - יפע
  - יפת
  - יצא
  - יצב
  - יצג
  - יצע
  - יצק
  - יצר
  - יצת
  - יקב
  - יקד
  - יקה
  - יקע
  - יקצ
  - יקר
  - יקש
  - ירא
  - ירב
  - ירד
  - ירה
  - ירח
  - ירט
  - ירכ
  - ירע
  - ירק
  - ירש
  - ישב
  - ישה
  - ישח
  - ישט
  - ישנ
  - ישע
  - ישר
  - ישש
  - ישׂמ
  - יתא
  - יתב
  - יתד
  - יתח
  - יתמ
  - יתר
  - כאב
  - כאה
  - כבב
  - כבד
  - כבה
  - כבל
  - כבס
  - כבע
  - כבר
  - כבש
  - כבשׂ
  - כדד
  - כדר
  - כהה
  - כהנ
  - כוה
  - כוח
  - כול
  - כומ
  - כונ
  - כור
  - כוש
  - כזב
  - כזר
  - כחד
  - כחח
  - כחל
  - כחש
  - כיד
  - כיה
  - כלא
  - כלב
  - כלה
  - כלח
  - כלל
  - כלמ
  - כלפ
  - כמה
  - כמז
  - כמנ
  - כמס
  - כמר
  - כנה
  - כננ
  - כנס
  - כנע
  - כנפ
  - כנר
  - כסא
  - כסה
  - כסח
  - כסל
  - כסמ
  - כסס
  - כספ
  - כעס
  - כעש
  - כפה
  - כפל
  - כפנ
  - כפס
  - כפפ
  - כפר
  - כפש
  - כפת
  - כרב
  - כרה
  - כרכ
  - כרמ
  - כרס
  - כרע
  - כרר
  - כרשׂ
  - כרת
  - כשב
  - כשׂב
  - כשׂה
  - כשל
  - כשפ
  - כשר
  - כתב
  - כתל
  - כתמ
  - כתנ
  - כתפ
  - כתר
  - כתש
  - כתת
  - לאב
  - לאה
  - לאט
  - לאכ
  - לאמ
  - לבא
  - לבב
  - לבה
  - לבט
  - לבנ
  - לבש
  - לגמ
  - להב
  - להג
  - להה
  - להט
  - להמ
  - להק
  - לוב
  - לוג
  - לוה
  - לוז
  - לוח
  - לוט
  - לול
  - לונ
  - לוע
  - לוצ
  - לוש
  - לחה
  - לחכ
  - לחמ
  - לחצ
  - לחש
  - לטא
  - לטה
  - לטש
  - לכד
  - למג
  - למד
  - למכ
  - לננ
  - לעב
  - לעג
  - לעה
  - לעז
  - לעט
  - לענ
  - לעע
  - לפד
  - לפת
  - לצצ
  - לקח
  - לקט
  - לקק
  - לקש
  - לשד
  - לתח
  - לתכ
  - לתע
  - מאד
  - מאה
  - מאמ
  - מאנ
  - מאס
  - מאר
  - מגג
  - מגנ
  - מגר
  - מדד
  - מהה
  - מהל
  - מהר
  - מוג
  - מוד
  - מוח
  - מוט
  - מוכ
  - מול
  - מומ
  - מונ
  - מוס
  - מוצ
  - מור
  - מוש
  - מטת
  - מזג
  - מזה
  - מזח
  - מזל
  - מזר
  - מחא
  - מחה
  - מחח
  - מחצ
  - מחק
  - מחר
  - מטט
  - מטר
  - מיי
  - מיק
  - מככ
  - מכר
  - מלא
  - מלה
  - מלח
  - מלט
  - מלכ
  - מלל
  - מלצ
  - מלק
  - מנה
  - מנח
  - מננ
  - מנע
  - מסה
  - מסכ
  - מסס
  - מסר
  - מעד
  - מעה
  - מעט
  - מעכ
  - מעל
  - מער
  - מצא
  - מצה
  - מצצ
  - מקק
  - מרא
  - מרג
  - מרד
  - מרה
  - מרח
  - מרט
  - מרכ
  - מרצ
  - מרק
  - מרר
  - משה
  - משח
  - משכ
  - משל
  - משק
  - משש
  - מתג
  - מתה
  - מתח
  - מתנ
  - מתק
  - מתת
  - נאד
  - נאה
  - נאמ
  - נאפ
  - נאצ
  - נאק
  - נאר
  - נבא
  - נבב
  - נבח
  - נבט
  - נבכ
  - נבל
  - נבע
  - נגב
  - נגד
  - נגה
  - נגז
  - נגח
  - נגנ
  - נגע
  - נגפ
  - נגר
  - נגש
  - נגשׂ
  - נדב
  - נדד
  - נדה
  - נדח
  - נדפ
  - נדר
  - נהג
  - נהה
  - נהל
  - נהמ
  - נהק
  - נהר
  - נוא
  - נוב
  - נוד
  - נוה
  - נוז
  - נוח
  - נוט
  - נול
  - נומ
  - נוס
  - נוע
  - נופ
  - נוצ
  - נור
  - נוש
  - נזד
  - נזה
  - נזל
  - נזמ
  - נזק
  - נזר
  - נחה
  - נחח
  - נחל
  - נחמ
  - נחס
  - נחצ
  - נחר
  - נחש
  - נחת
  - נטה
  - נטל
  - נטע
  - נטפ
  - נטר
  - נטש
  - נינ
  - ניר
  - נכא
  - נכד
  - נכה
  - נכח
  - נכל
  - נכס
  - נכר
  - נכת
  - נלל
  - נמל
  - נמר
  - נסג
  - נסה
  - נסח
  - נסכ
  - נסס
  - נסע
  - נסק
  - נעל
  - נעמ
  - נעע
  - נעצ
  - נער
  - נפה
  - נפח
  - נפכ
  - נפל
  - נפפ
  - נפצ
  - נפש
  - נפת
  - נצה
  - נצח
  - נצל
  - נצצ
  - נצר
  - נקא
  - נקב
  - נקד
  - נקה
  - נקמ
  - נקפ
  - נקק
  - נקר
  - נקש
  - נרד
  - נשא
  - נשׂא
  - נשב
  - נשׂג
  - נשה
  - נשׂה
  - נשכ
  - נשל
  - נשמ
  - נשפ
  - נשק
  - נשׂק
  - נשר
  - נשׂר
  - נשש
  - נשת
  - נתב
  - נתח
  - נתכ
  - נתנ
  - נתס
  - נתע
  - נתצ
  - נתק
  - נתר
  - נתש
  - סאה
  - סאנ
  - סבא
  - סבב
  - סבכ
  - סבל
  - סגג
  - סגד
  - סגל
  - סגנ
  - סגר
  - סדד
  - סדה
  - סדנ
  - סדר
  - סהר
  - סוב
  - סוג
  - סוד
  - סוה
  - סוח
  - סוכ
  - סוס
  - סופ
  - סור
  - סות
  - סחב
  - סחה
  - סחפ
  - סחס
  - סחש
  - סטה
  - סיר
  - סכה
  - סככ
  - סכל
  - סכנ
  - סכר
  - סכת
  - סלא
  - סלד
  - סלה
  - סלח
  - סלל
  - סלע
  - סלפ
  - סלת
  - סמכ
  - סמל
  - סממ
  - סמנ
  - סמר
  - סנה
  - סננ
  - סנפ
  - ססה
  - סעד
  - סעה
  - סעפ
  - סער
  - ספא
  - ספד
  - ספה
  - ספח
  - ספל
  - ספנ
  - ספפ
  - ספק
  - ספר
  - סקל
  - סרב
  - סרה
  - סרח
  - סרס
  - סרפ
  - סרר
  - סתה
  - סתמ
  - סתר
  - עבב
  - עבד
  - עבה
  - עבט
  - עבר
  - עבש
  - עבת
  - עגב
  - עגל
  - עגמ
  - עגנ
  - עגר
  - עדד
  - עדה
  - עדנ
  - עדפ
  - עדר
  - עדש
  - עוב
  - עוג
  - עוד
  - עוה
  - עוז
  - עוט
  - עול
  - עונ
  - עוע
  - עופ
  - עוצ
  - עוק
  - עור
  - עוש
  - עות
  - עזב
  - עזז
  - עזק
  - עזר
  - עטה
  - עטט
  - עטנ
  - עטפ
  - עטר
  - עטש
  - עיה
  - עימ
  - עינ
  - עיפ
  - עכס
  - עכר
  - עלג
  - עלה
  - עלז
  - עלט
  - עלל
  - עלמ
  - עלס
  - עלע
  - עלפ
  - עלצ
  - עלק
  - עמד
  - עמל
  - עממ
  - עמס
  - עמק
  - עמר
  - עמת
  - ענב
  - ענג
  - ענד
  - ענה
  - עננ
  - ענפ
  - ענק
  - ענש
  - עסס
  - עפא
  - עפה
  - עפל
  - עפפ
  - עפר
  - עצב
  - עצד
  - עצה
  - עצל
  - עצמ
  - עצר
  - עקב
  - עקד
  - עקה
  - עקל
  - עקר
  - עקש
  - ערב
  - ערג
  - ערד
  - ערה
  - ערכ
  - ערל
  - ערמ
  - ערס
  - ערפ
  - ערצ
  - ערק
  - ערר
  - ערשׂ
  - עשׂב
  - עשׂה
  - עשנ
  - עשק
  - עשׂק
  - עשר
  - עשׂר
  - עשש
  - עשׂשׂ
  - עשת
  - עתד
  - עתמ
  - עתק
  - עתר
  - עתת
  - פאה
  - פאר
  - פאת
  - פגג
  - פגל
  - פגע
  - פגר
  - פגש
  - פדה
  - פדע
  - פדר
  - פהה
  - פוא
  - פוג
  - פוה
  - פוז
  - פוח
  - פוכ
  - פול
  - פומ
  - פונ
  - פוצ
  - פוק
  - פור
  - פוש
  - פות
  - פזז
  - פזר
  - פחד
  - פחה
  - פחז
  - פחח
  - פחמ
  - פחת
  - פטד
  - פטר
  - פטש
  - פיד
  - פיק
  - פככ
  - פלא
  - פלג
  - פלד
  - פלה
  - פלח
  - פלט
  - פלכ
  - פלל
  - פלס
  - פלצ
  - פלש
  - פלשׂ
  - פנג
  - פנה
  - פנח
  - פננ
  - פנק
  - פסג
  - פסח
  - פסל
  - פסס
  - פעה
  - פעל
  - פעמ
  - פער
  - פצה
  - פצח
  - פצל
  - פצמ
  - פצע
  - פצצ
  - פצר
  - פקד
  - פקח
  - פקע
  - פרא
  - פרד
  - פרה
  - פרז
  - פרח
  - פרט
  - פרכ
  - פרמ
  - פרס
  - פרע
  - פרצ
  - פרק
  - פרר
  - פרש
  - פרשׂ
  - פרת
  - פשׂה
  - פשח
  - פשט
  - פשע
  - פשׂע
  - פשׂק
  - פשר
  - פשש
  - פשת
  - פתא
  - פתג
  - פתה
  - פתח
  - פתל
  - פתנ
  - פתע
  - פתר
  - פתת
  - צאא
  - צאה
  - צאל
  - צאנ
  - צבא
  - צבב
  - צבה
  - צבט
  - צבע
  - צבר
  - צבת
  - צבד
  - צדה
  - צדק
  - צהב
  - צהה
  - צהל
  - צהר
  - צוא
  - צוד
  - צוה
  - צוח
  - צול
  - צומ
  - צופ
  - צוצ
  - צוק
  - צור
  - צחה
  - צחח
  - צחנ
  - צחק
  - צחר
  - ציה
  - ציר
  - צלה
  - צלח
  - צלל
  - צלמ
  - צלע
  - צמא
  - צמד
  - צמה
  - צמח
  - צממ
  - צמק
  - צמר
  - צמת
  - צנא
  - צנה
  - צנח
  - צנמ
  - צננ
  - צנע
  - צנפ
  - צנק
  - צנר
  - צעד
  - צעה
  - צענ
  - צעע
  - צעפ
  - צעק
  - צער
  - צפד
  - צפה
  - צפח
  - צפנ
  - צפע
  - צפפ
  - צפר
  - צקל
  - צקק
  - צרב
  - צרה
  - צרח
  - צרכ
  - צרע
  - צרפ
  - צרר
  - קאה
  - קאמ
  - קבב
  - קבל
  - קבע
  - קבצ
  - קבר
  - קדד
  - קדה
  - קדח
  - קדמ
  - קדר
  - קדש
  - קהה
  - קהל
  - קוא
  - קוב
  - קוה
  - קוט
  - קול
  - קומ
  - קונ
  - קופ
  - קוצ
  - קור
  - קוש
  - קטב
  - קטט
  - קטל
  - קטנ
  - קטפ
  - קטר
  - קיר
  - קלא
  - קלה
  - קלח
  - קלט
  - קלל
  - קלס
  - קלע
  - קלש
  - קמח
  - קמט
  - קמל
  - קממ
  - קמצ
  - קמשׂ
  - קנא
  - קנה
  - קננ
  - קנצ
  - קסה
  - קסמ
  - קסס
  - קעע
  - קער
  - קפא
  - קפד
  - קפז
  - קפפ
  - קפצ
  - קצב
  - קצה
  - קצח
  - קצע
  - קצפ
  - קצצ
  - קצר
  - קקנ
  - קרא
  - קרב
  - קרד
  - קרה
  - קרח
  - קרמ
  - קרנ
  - קרס
  - קרע
  - קרצ
  - קרר
  - קרש
  - קשא
  - קשב
  - קשה
  - קשׂה
  - קשח
  - קשט
  - קשׂט
  - קשר
  - קשש
  - קשׂשׂ
  - קשת
  - ראה
  - ראמ
  - ראש
  - רבא
  - רבב
  - רבד
  - רבה
  - רבכ
  - רבע
  - רבצ
  - רבק
  - רגב
  - רגז
  - רגל
  - רגמ
  - רגנ
  - רגע
  - רגש
  - רדד
  - רדה
  - רדמ
  - רדפ
  - רהב
  - רהה
  - רהט
  - רוב
  - רוד
  - רוה
  - רוז
  - רוח
  - רומ
  - רוס
  - רוע
  - רופ
  - רוצ
  - רוק
  - רוש
  - רזה
  - רזח
  - רזמ
  - רחב
  - רחל
  - רחמ
  - רחפ
  - רחצ
  - רחק
  - רחש
  - רטב
  - רטה
  - רטט
  - רטפ
  - רטש
  - ריח
  - ריר
  - רכב
  - רככ
  - רכל
  - רכס
  - רכש
  - רמה
  - רמח
  - רמכ
  - רממ
  - רמנ
  - רמס
  - רמשׂ
  - רנה
  - רננ
  - רסס
  - רעב
  - רעד
  - רעה
  - רעל
  - רעמ
  - רענ
  - רעע
  - רעפ
  - רעצ
  - רעש
  - רפא
  - רפד
  - רפה
  - רפס
  - רפפ
  - רפק
  - רפש
  - רפשׂ
  - רפת
  - רצד
  - רצה
  - רצח
  - רצע
  - רצפ
  - רצצ
  - רקב
  - רקד
  - רקה
  - רקח
  - רקמ
  - רקע
  - רקק
  - רשה
  - רשמ
  - רשע
  - רשפ
  - רשש
  - רתח
  - רתמ
  - רתק
  - רתת
  - שאב
  - שאג
  - שאה
  - שאט
  - שאל
  - שאנ
  - שאפ
  - שאר
  - שבב
  - שבה
  - שבח
  - שבט
  - שבל
  - שבס
  - שבע
  - שבצ
  - שבר
  - שבת
  - שגא
  - שגג
  - שגה
  - שגח
  - שגל
  - שגע
  - שגר
  - שדד
  - שדה
  - שדפ
  - שהמ
  - שוא
  - שוב
  - שוד
  - שוה
  - שוח
  - שוט
  - שול
  - שומ
  - שוע
  - שופ
  - שוק
  - שור
  - שוש
  - שות
  - שזפ
  - שזר
  - שחד
  - שחה
  - שחח
  - שחט
  - שחל
  - שחנ
  - שחס
  - שחפ
  - שחצ
  - שחק
  - שחר
  - שחת
  - שטח
  - שטט
  - שטפ
  - שטר
  - שיי
  - שיר
  - שכב
  - שכח
  - שככ
  - שכל
  - שכמ
  - שכנ
  - שכר
  - שלב
  - שלג
  - שלה
  - שלח
  - שלט
  - שלכ
  - שלל
  - שלמ
  - שלפ
  - שלש
  - שמד
  - שמה
  - שמט
  - שממ
  - שמנ
  - שמע
  - שמצ
  - שמר
  - שמש
  - שנא
  - שנב
  - שנה
  - שננ
  - שנס
  - שסה
  - שסס
  - שסע
  - שספ
  - שעה
  - שעט
  - שעל
  - שענ
  - שעע
  - שער
  - שפה
  - שפח
  - שפט
  - שפכ
  - שפל
  - שפע
  - שפפ
  - שפר
  - שפת
  - שצפ
  - שקד
  - שקה
  - שקט
  - שקל
  - שקמ
  - שקע
  - שקפ
  - שקצ
  - שקק
  - שקר
  - שרב
  - שרה
  - שרצ
  - שרק
  - שרר
  - שרש
  - שרת
  - ששא
  - ששה
  - ששר
  - שתה
  - שתל
  - שתמ
  - שתנ
  - שתע
  - שתק
  - שתת
  - שׂאר
  - שׂבכ
  - שׂבע
  - שׂבר
  - שׂגא
  - שׂגב
  - שׂגג
  - שׂגה
  - שׂדד
  - שׂדה
  - שׂדר
  - שׂהד
  - שׂהה
  - שׂהר
  - שׂוג
  - שׂוד
  - שׂוט
  - שׂוכ
  - שׂומ
  - שׂור
  - שׂושׂ
  - שׂחה
  - שׂחח
  - שׂחט
  - שׂהפ
  - שׂחק
  - שׂטה
  - שׂטמ
  - שׂטנ
  - שׂיב
  - שׂיח
  - שׂכה
  - שׂככ
  - שׂכל
  - שׂכר
  - שׂכת
  - שׂלה
  - שׂלמ
  - שׂמח
  - שׂמכ
  - שׂמל
  - שׂממ
  - שׂמר
  - שׂנא
  - שׂעפ
  - שׂער
  - שׂפה
  - שׂפח
  - שׂפנ
  - שׂפק
  - שׂקד
  - שׂקק
  - שׂקר
  - שׂרג
  - שׂרד
  - שׂרה
  - שׂרט
  - שׂרכ
  - שׂרע
  - שׂרפ
  - שׂרק
  - שׂרר
  - שׂרת
  - שׂתמ
  - שׂתר
  - שׂתת
  - תאב
  - תאה
  - תאמ
  - תאנ
  - תאר
  - תבנ
  - תגה
  - תהה
  - תוה
  - תוכ
  - תומ
  - תור
  - תוש
  - תזז
  - תחר
  - תחת
  - תכה
  - תככ
  - תכל
  - תכנ
  - תלא
  - תלה
  - תלל
  - תלע
  - תמה
  - תמז
  - תמכ
  - תמל
  - תממ
  - תמר
  - תנה
  - תנכ
  - תננ
  - תעב
  - תעה
  - תעע
  - תפה
  - תפל
  - תפפ
  - תפר
  - תפשׂ
  - תקנ
  - תקע
  - תקפ
  - תרז
  - תרח
  - תרנ
  - תרש
  - תשע
