name: Update Commit Info

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  update-commit-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository information
        id: repo-info
        run: |
          echo "REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "AUTHOR_NAME=$(git log -1 --pretty=%an)" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=$(git log -1 --pretty=%ae)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --pretty=%cd)" >> $GITHUB_ENV
      - name: Update commitInfo.json
        run: |
          cat <<EOF > commitInfo.json
          {
            "repo": "${{ env.REPO_NAME }}",
            "branch": "${{ env.BRANCH_NAME }}",
            "commit": "${{ env.COMMIT_HASH }}",
            "date": "${{ env.COMMIT_DATE }}"
            "message": "${{ env.COMMIT_MESSAGE }}",
            "author": "${{ env.AUTHOR_NAME }}",
            "email": "${{ env.AUTHOR_EMAIL }}"
          }
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add commitInfo.json
          git commit -m "Update commitInfo.json"
          git push origin ${{ env.BRANCH_NAME }}
